### ISSUE TITLE
400 error

### ISSUE THREAD

**Issue by shersch** [olljanat/portainer-vsts-deploy#3]
Hi,

When trying to use this extension, I get the following error:

```
2022-05-31T13:58:09.9664527Z Get list of existing stacks
2022-05-31T13:58:09.9871071Z Not found stack STACK_NAME, creating...
2022-05-31T13:58:10.2796852Z ##[error]The remote server returned an error: (400) Bad Request.
```

As far as I can tell, everything is set up correctly, but I can't find any further details about this error.

**Comment by olljanat** [comment]
Which Portainer version you are using? Sounds that they have changed API somehow.

**Comment by shersch** [comment]
business edition 2.13.1

**Comment by shersch** [comment]
after taking a look at your code, i think this may be my own fault.  i didn't have swarm initialized on my host.  now that i do, i'm getting 500 error.  my guess is that i need to change some settings now that swarm is enabled.
`2022-06-03T14:10:39.8818251Z ##[error]The remote server returned an error: (500) Internal Server Error.`

**Comment by shersch** [comment]
the issue was caused by my own ignorance.  after getting swarm going, i was getting the 500 errors.  after looking at portainer's logs, i saw that my compose file was not set up properly.  it is working now.  thank you!
